#!/usr/bin/env bash
# installs nginx HTTP server on a server and make it listen on port 80

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart
