#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me is redirected
# to another page

location="https://www.youtube.com/watch?v=QH2-TGUlwu4"
conf="server_name\ _;\nrewrite ^/redirect_me/?$ $location permanent;"

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

sed -i "s|server_name\ _;|$conf|" /etc/nginx/sites-available/default
service nginx restart