#!/usr/bin/env bash
# Configures HAProxy so that it sends requests to two websites

# Update packages
apt update

# Add HAProxy PPA
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0 -y

# Install HAProxy
apt-get install -y haproxy=2.0.\*

# Configures HAProxy
config_file='/etc/haproxy/haproxy.cfg'
f_name='frontend alx_web'
f_bind='bind *:80'
f_mode='mode http'
f_default='default_backend alx_web_server'
f_config="$f_name\n\t$f_mode\n\t$f_bind\n\t$f_default"

b_name='backend alx_web_server'
b_mode='mode http'
b_balance='balance roundrobin'
b_server1='server web-01 54.157.149.148:80 check'
b_server2='server web-02 100.25.167.197:80 check'
b_config="$b_name\n\t$b_mode\n\t$b_balance\n\t$b_server1\n\t$b_server2"

if ! grep -q "$f_name" $config_file; then
    echo -e "\n$f_config" >> $config_file
fi

echo -e "\n$b_config" >> $config_file
service haproxy restart
