#!/usr/bin/env bash
# init that manages manage_my_process file

PROCESS=manage_my_process
FILE=/var/run/my_process.pid
if (( $# == 1 )); then
    if [[ "$1" == "start" ]]; then
        ./"$PROCESS" &
        echo "$!" > "$FILE"
        echo "manage_my_process started"
    elif [[ "$1" == "stop" ]]; then
        kill "$(cat $FILE)"
        rm -f "$FILE"
        echo "manage_my_process stopped"
    elif [[ "$1" == "restart" ]]; then
        kill "$(cat $FILE)"
        rm -f "$FILE"
        ./"$PROCESS" &
        echo "$!" > "$FILE"
        echo "manage_my_process restarted"
    else
        echo "Usage: manage_my_process {start|stop|restart}"
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
