#!/usr/bin/env bash
# displays number from 1 to 20

i=0
while (( i < 20 )); do
    echo $((i + 1))
    case $i in
        3) echo "bad luck from China"
           ;;
        8) echo "bad luck from Japan"
           ;;
        16) echo "bad luck from Italy"
            ;;
    esac
    ((i++))
done
