#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

i=0
while (( i <= 12 )); do
    j=1
    echo "Hour: $i"
    while (( j < 60 )); do
        echo "$j"
        ((j++))
    done
    ((i++))
done
