#!/usr/bin/env bash
# gives information about the school file

file="holbertonschool"
if [ -e "$file" ]; then
	echo "holbertonschool file exits"
	if [ -s "$file" ]; then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi

	if [ -f "$file" ]; then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exit"
fi
