#!/usr/bin/env bash
# gives information about the school file

FILE="holbertonschool"
if [ -e "$FILE" ]; then
	echo "holbertonschool file exits"
	if [ -s "$FILE" ]; then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi

	if [ -f "$FILE" ]; then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exit"
fi
